import os
from pyshortcuts import make_shortcut

# Path to the executable generated by cx_Freeze
exe_path = os.path.join(os.path.dirname(__file__), 'build', 'exe.win32-3.8', 'SexyMath.exe')

# Create a shortcut on the desktop
make_shortcut(exe_path, name='SexyMath', description='SexyMath Application', icon='MyFirstApp.ico')

print("Shortcut created on desktop.")
